# Site settings
title: Sebastian Marulanda
email: sebastian@marulanda.me
description: > # this means to ignore newlines until "baseurl:"
  Sebastian Marulanda is an Atlanta based web developer and designer.
permalink: /:title
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://marulanda.me" # the base hostname & protocol for your site
twitter_username: smarulanda
github_username: smarulanda

# Build settings
markdown: kramdown
highlighter: pygments 

# Variables
s3: "https://s3.amazonaws.com/marulanda.me"
facebook_link: "https://facebook.com/smarulanda3"
google_plus_link: "https://plus.google.com/+SebastianMarulanda"
twitter_link: "https://twitter.com/smarulanda"
github_link: "https://github.com/smarulanda"